### ISSUE TITLE
Setting the log level by dlt-viewer 

### ISSUE THREAD

**Issue by Manojcv55** [COVESA/dlt-daemon#306] opened 2021-04-28 11:24 UTC
I have faced the issue , if application are using dlt_register_context_ll_ts() and dlt_set_application_ll_ts_limit() and setting log level as verbose , these log will be seen in dlt-viewer , even through the log level in dlt-viewer and conf is info.

Is it know behavior any suggestion to fix this ?

**Comment by ssugiura** [comment] 2021-05-12 05:04
@Manojcv55 This is an expected behavior because `dlt_set_application_ll_ts_limit()` call forces all registered app/contexts to update to specified log level, so settings of DLT clients would be overwritten at that moment.
One workaround is to send set log level control message from DLT client (dlt-viewer), then it will be again updated to corresponding log level.

**Comment by thanhbnq** [comment] 2022-05-09 03:55
Thank you all for discussion.
Since no more concerns, I would like to close this issue.
Thanh

**Closed by thanhbnq** 2022-05-09 03:55 UTC
