### ISSUE TITLE
dlt-daemon can't bind to link-local Ipv6 addresses

### ISSUE THREAD

**Issue by loayezzat** [COVESA/dlt-daemon#428] opened 2022-12-13 06:45 UTC
version: [v2.18.8](https://github.com/COVESA/dlt-daemon/releases/tag/v2.18.8)
Providing the Ipv4 addresses, through the **BindAddress** parameter in [dlt.conf](https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt.conf.5.md), of either the 'lo' or 'eth' interfaces works fine and the dlt-daemon bind itself and listens to client connections without any issues. However, providing the Ipv6 address of the 'eth' interface doesn't work fine and the dlt-daemon can't bind itself.

DLT Log:
```
[  206.530986]~DLT~ 2516~INFO     ~Activate connection type: 5
[  206.530997]~DLT~ 2516~INFO     ~dlt_daemon_socket_open: Socket created
[  206.531012]~DLT~ 2516~WARNING  ~dlt_daemon_socket_open: bind() error 22: Invalid argument
[  206.531014]~DLT~ 2516~ERROR    ~Could not initialize main socket.
[  206.531016]~DLT~ 2516~CRITICAL ~Initialization of local connections failed!
```

Suggested solution:
In the function **dlt_daemon_socket_open**, the field **sin6_scope_id** of struct **sockaddr_in6**  shall be set somehow before binding to the socket.

**Comment by lti9hc** [comment] 2023-04-26 06:41
Hello @loayezzat
 
By default, IPv6 is enabled

My network interface

$ ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:112 errors:0 dropped:0 overruns:0 frame:0
          TX packets:112 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:9878 (9.8 KB)  TX bytes:9878 (9.8 KB)

Currently, I could not reproduce on my environment.

$ dlt-daemon
[   43.909800]~DLT~ 2350~NOTICE   ~Starting DLT Daemon; DLT Package Version: 2.18.8 STABLE, Package Revision: v2.18.8_66_g44e4e76, build on Apr 25 2023 16:32:05
-SYSTEMD -SYSTEMD_WATCHDOG -TEST -SHM

[   43.909848]~DLT~ 2350~INFO     ~FIFO size: 65536
[   43.909857]~DLT~ 2350~WARNING  ~Unable to set send timeout Socket operation on non-socket.
[   43.909858]~DLT~ 2350~INFO     ~Activate connection type: 5
[   43.909865]~DLT~ 2350~INFO     ~dlt_daemon_socket_open: Socket created
[   43.909871]~DLT~ 2350~INFO     ~dlt_daemon_socket_open: Listening on ip 0.0.0.0 and port: 3490
[   43.909873]~DLT~ 2350~INFO     ~dlt_daemon_socket_open: Socket send queue size: 16384
[   43.909897]~DLT~ 2350~INFO     ~Activate connection type: 1
[   43.909910]~DLT~ 2350~INFO     ~Activate connection type: 9
[   43.909917]~DLT~ 2350~INFO     ~Cannot open configuration file: /tmp/dlt-runtime.cfg
[   43.909921]~DLT~ 2350~INFO     ~Ringbuffer configuration: 500000/10000000/500000
[   43.910033]~DLT~ 2350~NOTICE   ~Failed to open ECU Software version file.
[   43.910043]~DLT~ 2350~WARNING  ~Unable to set send timeout Socket operation on non-socket.
[   43.910044]~DLT~ 2350~INFO     ~Activate connection type: 6
[   43.910045]~DLT~ 2350~INFO     ~Switched to buffer state for socket connections.
[   43.910049]~DLT~ 2350~WARNING  ~dlt_daemon_applications_load: cannot open file /tmp/dlt-runtime-application.cfg: No such file or directory


Could you please share me the way you provide the Ipv6 address of the 'eth' interface?

Thank you

**Comment by michael-methner** [comment] 2023-05-10 09:07
Closing as we did not get a response from the reporter

**Closed by michael-methner** 2023-05-10 09:07 UTC
