### ISSUE TITLE
Log level is not getting changed by dlt-control utility

### ISSUE THREAD

**Issue by jtr-work** [COVESA/dlt-daemon#427] opened 2022-12-07 10:01 UTC
Hi Team,

I am trying to set Log level of on application on the go, using dlt-control as follows.I am trying to turning off the logs basically by "0"

dlt-control -c NSMC -a NSMC -l 0 localhost
getting out put as follows.
[ 3951.873359]~DLT~20378~INFO     ~dlt_client_send_ctrl_msg: Control message forwarded : DLT_SERVICE_ID_SET_LOG_LEVEL.

but while checking by using following command
dlt-control -j -u

output
CTID:NSM-  5 -1 Context for the NSM
CTID:NSMA -1 -1 Context for the NSMA
CTID:NSMC  5 -1 Context for the NSM
APID:NSMC Node State Machine

Seems it is not getting changed

following are the information regarding version(2.18.8) of dlt-daemon I am sing

root@me-l17x:~# dlt-daemon --version
Unknown option `--'.
DLT Package Version: 2.18.8 STABLE, Package Revision: v2.18.8_23_g6a3bd90, build on Dec  1 2022 09:12:50
+SYSTEMD +SYSTEMD_WATCHDOG -TEST -SHM
Usage: dlt-daemon [options]
Options:
  -d            Daemonize
  -h            Usage
  -c filename   DLT daemon configuration file (Default: /etc/dlt.conf)
  -t directory  Directory for local fifo and user-pipes (Default: /tmp)
                (Applications wanting to connect to a daemon using a
                custom directory need to be started with the environment
                variable DLT_PIPE_DIR set appropriately)
  -p port       port to monitor for incoming requests (Default: 3490)
                (Applications wanting to connect to a daemon using a custom
                port need to be started with the environment variable
                DLT_DAEMON_TCP_PORT set appropriately)
option_handling() failed!

could you please comment/reply  on this?

**Comment by thanhbnq** [comment] 2022-12-07 10:52
Hello @jtr-work ,

1. Are you also using offline logstorage feature while doing test?
2. In case you can help to reproduce, please help to collect the logs by following the steps (in your dlt.conf)
2.1 Set LoggingMode = 2
2.2 Set LoggingFilename = /tmp/dlt.log
3. Enable more verbose log for dlt-control by adding "-v" for your commands.

Then please share with us "dlt.log" from 2.2 and output of dlt-control with "-v"

Thanh

**Comment by lti9hc** [comment] 2022-12-13 04:44
Hello @jtr-work,
Sorry for my reponse late
Base on your dlt.log file, I saw "dlt_logstorage_write: ApId-CtId-EcuId [(null)]-[(null)]-[TCA]" log, it means you are using offline logstorage feature
Did you set MaintainLogstorageLogLevel in dlt_logstorage.conf file?
In case you set MaintainLogstorageLogLevel to ON, please set it to OFF and test again
Thank you,

**Comment by jtr-work** [comment] 2023-01-25 06:34
Hello @lti9hc ,

Sorry for the late reply.
I have checked and I see that I am not setting MaintainLogstorageLoglevel to ON explicitly.

I will the attach the dlt.conf file as well as the result of the experiment I did so far.
I took DLT Package Version: 2.18.4 STABLE at this moment.
[dlt.log](https://github.com/COVESA/dlt-daemon/files/10496758/dlt.log)
[experiment.txt](https://github.com/COVESA/dlt-daemon/files/10496760/experiment.txt)

Thank you...!

**Comment by lti9hc** [comment] 2023-02-08 04:05
Hello @jtr-work 
I checked in experiment .txt file and found that you used command "dlt-control -a NSM -l 4 localhost".
I think you have wrong for this command, it should be used "dlt-control -a NSMC -l 4 localhost"

more information:
-a for control message application id
-c for control message context id

Please test it again and let me know

Thank you very much!

**Comment by lvklevankhanh** [comment] 2023-02-15 09:02
close this ticket because it is not a bug
if you got this issue in the future, you can reopen it
thank you

**Closed** 2023-02-15 09:03 UTC
