### ISSUE TITLE
dlt installation on QNX

### ISSUE THREAD

**Issue by kk29-val** [COVESA/dlt-daemon#550] opened 2023-10-12 08:35 UTC
Hello, After cross compiling DLT for QNX ,I copy dlt-daemon,dlt-qnx-system binaries in QNX and then I run "./dlt-daemon" but I got this issue......

 TARGET= Q drive 3
 OS= QNX

[ 5435.656876]~DLT~1163315~NOTICE   ~Starting DLT Daemon; DLT Package Version: 2.18.10 STABLE, Package Revision: v2.18.10_6_g4ed1b97, build on Oct 12 2023 11:00:03
-SYSTEMD -SYSTEMD_WATCHDOG -TEST -SHM
[ 5435.656876]~DLT~1163315~WARNING  ~dlt_daemon_unix_socket_open: bind() error (Permission denied)
[ 5435.656876]~DLT~1163315~CRITICAL ~Could not create and open app socket.
[ 5435.656876]~DLT~1163315~ERROR    ~Unable to initialize app socket.
[ 5435.656876]~DLT~1163315~CRITICAL ~Initialization of local connections failed!

**Comment by minminlittleshrimp** [comment] 2023-10-12 13:18
Hello @kk29-val 
As Michael mentioned in some of your duplicated issues, this is in fact out of scope and cannot be classified as issues, bugs. I recommend you to put this topic in discussion since dlt installation on an OS is not a bug at all. Besides, from now on we will not support any case about installation in issue tag.
If in any case you think that there is a bug, then please kindly clarify the issue with debug logs, coredump, memory check logs, etc
Hence, I will close this issue.
Thanks for your understanding

**Comment by minminlittleshrimp** [comment] 2023-10-12 13:19
Close due to not a bug

**Closed by minminlittleshrimp** 2023-10-12 13:19 UTC
