### ISSUE TITLE
Verbosity of a application is getting changed when tried from dlt-control

### ISSUE THREAD

**Issue by userofopenssl** [COVESA/dlt-daemon#310] opened 2021-06-08 13:48 UTC
I am setting the application verbosity using dlt-control utility using following command:

dlt-control -l <LogLevel> -a <AppName> -c <ContextName> localhost.

setup
1) captured the dlt traces using dlt viewer(dlt package: 2.18.0). 
2) Send "Default Log Level,Trace Status and Verbose Mode" if online -> checkbox UNCHECKED in ECU CONFIGURATION
3) Update data in DLT if online -> checkbox UNCHECKED in ECU CONFIGURATION

Could you please give me pointers why dlt-daemon is not taking actions for changing verbosity(loglevel) when signal sent from dlt-control utility.

**Comment by userofopenssl** [comment] 2021-06-08 14:05
output:
root@fpdm-c112:~# dlt-control -l 1 -a OneE -c Glue localhost -v
[  147.966316]~DLT~ 2440~INFO     ~Init dlt client struct with default port: 3490.
[  147.966493]~DLT~ 2440~INFO     ~dlt_file_init()
[  147.966507]~DLT~ 2440~INFO     ~dlt_message_init()
[  147.966517]~DLT~ 2440~INFO     ~dlt_filter_init()
[  147.967662]~DLT~ 2440~WARNING  ~connect() failed! Connection refused
Connected to DLT daemon (localhost)
Set log level:
AppId: OneE
ConId: Glue
Loglevel: 1
[  147.968654]~DLT~ 2440~INFO     ~Control message forwarded : DLT_SERVICE_ID_SET_LOG_LEVEL
Cleanup dlt client
[  148.968920]~DLT~ 2440~INFO     ~dlt_file_free()
[  148.968941]~DLT~ 2440~INFO     ~dlt_message_free()
[  148.968960]~DLT~ 2440~INFO     ~dlt_filter_free()

**Comment by ssugiura** [comment] 2021-08-06 05:14
@userofopenssl 
Sorry that I missed to reply this for long time. Is this still reproducible?
Tried to reproduce this on my end, but dlt-control is working as expected, means once I set loglevel to 1 only FATAL logs are sent to DLT viewer.

**Comment by thanhbnq** [comment] 2022-03-30 06:45
Hi @userofopenssl ,

Do you have any updates on this topic?
Based on comment from @ssugiura , dlt-control seems to be still working fine.

Regarding your comment https://github.com/COVESA/dlt-daemon/issues/310#issuecomment-856798403,
(The format of text seems to be broken by strikethrough)
it looks like the dlt-control is not able to connect dlt-daemon with warning "connect() failed! Connection refused".

Please kindly provide your updates if you need further supports

Thank you,
Thanh

**Comment by thanhbnq** [comment] 2022-05-09 03:57
Hello @userofopenssl ,
I would like to close this issue since you have no updates for long time.
Thank you both for discussion.
Thanh

**Closed by thanhbnq** 2022-05-09 03:57 UTC
