### ISSUE TITLE
Is there any log amount profiler?

### ISSUE THREAD

**Issue by pullingtab** [COVESA/dlt-daemon#506] opened 2023-07-20 02:40 UTC
There always is a mountain of log in a system. But the hard disk space is limited. We have to decide which process/module produces too much log. Is there already a tool for this kind of job?
I imagine this tool can tell me how much data a context is producing per second. And I can set a maximum amount of data that a context is allowed to produce. Once it exceeds this limitation, it's log will be abandon until next window.

**Comment by minminlittleshrimp** [comment] 2023-07-24 03:06
Hello @pullingtab ,
Thanks for your interest in DLT topic.
We are currently constructing a so-called dlt-statistic to illustrate all apps and contexts data (number of logs, kB/s log transmitted, etc).
It is going to be implemented and planned for an official release soon.
Regards,
DLT team

**Comment by pullingtab** [comment] 2023-07-28 17:44
> Hello @pullingtab ,
> Thanks for your interest in DLT topic.
> We are currently constructing a so-called dlt-statistic to illustrate all apps and contexts data (number of logs, kB/s log transmitted, etc).
> It is going to be implemented and planned for an official release soon.
> Hope we will have your distribution in this statistic topic.
> Regards,
> DLT team

sounds great !
but it would be better if we could control how much log is allowed to be written into the disk.
do you have any plan for that?

**Comment by minminlittleshrimp** [comment] 2023-07-29 05:15
Hello,
Have you trìed logstorage yet?

https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_offline_logstorage.md

This feature allows you to control log flow by setting some log filters to filter the log.

Regards

**Comment by pullingtab** [comment] 2023-07-31 06:58
> Hello, Have you tried logstorage yet?
> 
> https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_offline_logstorage.md
> 
> This feature allows you to control log flow by setting some log filters to filter the logs by log level, log file size, etc
> 
> Regards

I tried this. This feature is a great help. But what i really want is something like speed-limiter. For example, i can set that a context can send 500 rows of log in 3 seconds. If this context send one more log, this log will be abandoned.

**Comment by minminlittleshrimp** [comment] 2023-07-31 17:27
Hello @pullingtab 
Sound interesting, I will check our component to see if this feature available, else we could plan for the implementation.
Thank you

**Comment by pullingtab** [comment] 2023-08-06 09:25
> Hello @pullingtab Sound interesting, I will check our component to see if this feature available, else we could plan for the implementation. Thank you

it would be great help if there already is such function. because we can be sure of how long ago that the log can trace

**Comment by michael-methner** [comment] 2023-08-09 09:42
I am closing this one as it is a feature request and not a bug.
DLT team will not implement such a feature as it is not on our roadmap. 
Please feel free to upstream such a feature. Please keep in mind that it is not possible to perform resource intensive operations on each log message. So when you like to upstream, such a feature should not have any impact on existing system. E.g. by having it switched off by a compile flag by default.

In future, please use discussions forum here on github to discuss new features. 

Kind regards,
Michael

**Closed by michael-methner** 2023-08-09 09:42 UTC
